// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Morpheus.Infraestrutura.Persistencia;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Morpheus.Infraestrutura.Persistencia.Migracoes
{
    [DbContext(typeof(MorpheusDbContext))]
    [Migration("20260722000739_TituloFinalidadeESituacaoDoImovel")]
    partial class TituloFinalidadeESituacaoDoImovel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_name");

                    b.HasKey("Id")
                        .HasName("pk_roles");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("9f1b7a10-0000-4000-8000-000000000001"),
                            ConcurrencyStamp = "9f1b7a10-0000-4000-8000-000000000001",
                            Name = "dono",
                            NormalizedName = "DONO"
                        },
                        new
                        {
                            Id = new Guid("9f1b7a10-0000-4000-8000-000000000002"),
                            ConcurrencyStamp = "9f1b7a10-0000-4000-8000-000000000002",
                            Name = "corretor",
                            NormalizedName = "CORRETOR"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("Id")
                        .HasName("pk_role_claims");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_role_claims_role_id");

                    b.ToTable("role_claims", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClaimType = "permissao",
                            ClaimValue = "imovel.ler",
                            RoleId = new Guid("9f1b7a10-0000-4000-8000-000000000001")
                        },
                        new
                        {
                            Id = 2,
                            ClaimType = "permissao",
                            ClaimValue = "imovel.escrever",
                            RoleId = new Guid("9f1b7a10-0000-4000-8000-000000000001")
                        },
                        new
                        {
                            Id = 3,
                            ClaimType = "permissao",
                            ClaimValue = "lead.ler",
                            RoleId = new Guid("9f1b7a10-0000-4000-8000-000000000001")
                        },
                        new
                        {
                            Id = 4,
                            ClaimType = "permissao",
                            ClaimValue = "lead.atender",
                            RoleId = new Guid("9f1b7a10-0000-4000-8000-000000000001")
                        },
                        new
                        {
                            Id = 5,
                            ClaimType = "permissao",
                            ClaimValue = "visita.agendar",
                            RoleId = new Guid("9f1b7a10-0000-4000-8000-000000000001")
                        },
                        new
                        {
                            Id = 6,
                            ClaimType = "permissao",
                            ClaimValue = "dossie.criar",
                            RoleId = new Guid("9f1b7a10-0000-4000-8000-000000000001")
                        },
                        new
                        {
                            Id = 7,
                            ClaimType = "permissao",
                            ClaimValue = "dossie.ler",
                            RoleId = new Guid("9f1b7a10-0000-4000-8000-000000000001")
                        },
                        new
                        {
                            Id = 8,
                            ClaimType = "permissao",
                            ClaimValue = "dossie.aprovar_item",
                            RoleId = new Guid("9f1b7a10-0000-4000-8000-000000000001")
                        },
                        new
                        {
                            Id = 9,
                            ClaimType = "permissao",
                            ClaimValue = "dossie.baixar_anexo",
                            RoleId = new Guid("9f1b7a10-0000-4000-8000-000000000001")
                        },
                        new
                        {
                            Id = 10,
                            ClaimType = "permissao",
                            ClaimValue = "magiclink.emitir",
                            RoleId = new Guid("9f1b7a10-0000-4000-8000-000000000001")
                        },
                        new
                        {
                            Id = 11,
                            ClaimType = "permissao",
                            ClaimValue = "magiclink.revogar",
                            RoleId = new Guid("9f1b7a10-0000-4000-8000-000000000001")
                        },
                        new
                        {
                            Id = 12,
                            ClaimType = "permissao",
                            ClaimValue = "relatorio.gerar",
                            RoleId = new Guid("9f1b7a10-0000-4000-8000-000000000001")
                        },
                        new
                        {
                            Id = 13,
                            ClaimType = "permissao",
                            ClaimValue = "relatorio.enviar",
                            RoleId = new Guid("9f1b7a10-0000-4000-8000-000000000001")
                        },
                        new
                        {
                            Id = 14,
                            ClaimType = "permissao",
                            ClaimValue = "usuario.gerenciar",
                            RoleId = new Guid("9f1b7a10-0000-4000-8000-000000000001")
                        },
                        new
                        {
                            Id = 15,
                            ClaimType = "permissao",
                            ClaimValue = "tenant.configurar",
                            RoleId = new Guid("9f1b7a10-0000-4000-8000-000000000001")
                        },
                        new
                        {
                            Id = 16,
                            ClaimType = "permissao",
                            ClaimValue = "faturamento.gerenciar",
                            RoleId = new Guid("9f1b7a10-0000-4000-8000-000000000001")
                        },
                        new
                        {
                            Id = 17,
                            ClaimType = "permissao",
                            ClaimValue = "metricas.ler",
                            RoleId = new Guid("9f1b7a10-0000-4000-8000-000000000001")
                        },
                        new
                        {
                            Id = 18,
                            ClaimType = "permissao",
                            ClaimValue = "imovel.ler",
                            RoleId = new Guid("9f1b7a10-0000-4000-8000-000000000002")
                        },
                        new
                        {
                            Id = 19,
                            ClaimType = "permissao",
                            ClaimValue = "imovel.escrever",
                            RoleId = new Guid("9f1b7a10-0000-4000-8000-000000000002")
                        },
                        new
                        {
                            Id = 20,
                            ClaimType = "permissao",
                            ClaimValue = "lead.ler",
                            RoleId = new Guid("9f1b7a10-0000-4000-8000-000000000002")
                        },
                        new
                        {
                            Id = 21,
                            ClaimType = "permissao",
                            ClaimValue = "lead.atender",
                            RoleId = new Guid("9f1b7a10-0000-4000-8000-000000000002")
                        },
                        new
                        {
                            Id = 22,
                            ClaimType = "permissao",
                            ClaimValue = "visita.agendar",
                            RoleId = new Guid("9f1b7a10-0000-4000-8000-000000000002")
                        },
                        new
                        {
                            Id = 23,
                            ClaimType = "permissao",
                            ClaimValue = "dossie.criar",
                            RoleId = new Guid("9f1b7a10-0000-4000-8000-000000000002")
                        },
                        new
                        {
                            Id = 24,
                            ClaimType = "permissao",
                            ClaimValue = "dossie.ler",
                            RoleId = new Guid("9f1b7a10-0000-4000-8000-000000000002")
                        },
                        new
                        {
                            Id = 25,
                            ClaimType = "permissao",
                            ClaimValue = "dossie.aprovar_item",
                            RoleId = new Guid("9f1b7a10-0000-4000-8000-000000000002")
                        },
                        new
                        {
                            Id = 26,
                            ClaimType = "permissao",
                            ClaimValue = "dossie.baixar_anexo",
                            RoleId = new Guid("9f1b7a10-0000-4000-8000-000000000002")
                        },
                        new
                        {
                            Id = 27,
                            ClaimType = "permissao",
                            ClaimValue = "magiclink.emitir",
                            RoleId = new Guid("9f1b7a10-0000-4000-8000-000000000002")
                        },
                        new
                        {
                            Id = 28,
                            ClaimType = "permissao",
                            ClaimValue = "magiclink.revogar",
                            RoleId = new Guid("9f1b7a10-0000-4000-8000-000000000002")
                        },
                        new
                        {
                            Id = 29,
                            ClaimType = "permissao",
                            ClaimValue = "relatorio.gerar",
                            RoleId = new Guid("9f1b7a10-0000-4000-8000-000000000002")
                        },
                        new
                        {
                            Id = 30,
                            ClaimType = "permissao",
                            ClaimValue = "relatorio.enviar",
                            RoleId = new Guid("9f1b7a10-0000-4000-8000-000000000002")
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_claims");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_claims_user_id");

                    b.ToTable("user_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text")
                        .HasColumnName("provider_key");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text")
                        .HasColumnName("provider_display_name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("LoginProvider", "ProviderKey")
                        .HasName("pk_user_logins");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_logins_user_id");

                    b.ToTable("user_logins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId")
                        .HasName("pk_user_roles");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_user_roles_role_id");

                    b.ToTable("user_roles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("UserId", "LoginProvider", "Name")
                        .HasName("pk_user_tokens");

                    b.ToTable("user_tokens", (string)null);
                });

            modelBuilder.Entity("Morpheus.Dominio.Imoveis.Imovel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CodigoDeReferencia")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("codigo_de_referencia");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("endereco");

                    b.Property<string>("Finalidade")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("finalidade");

                    b.Property<Guid>("OrganizacaoId")
                        .HasColumnType("uuid")
                        .HasColumnName("organizacao_id");

                    b.Property<string>("Situacao")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("situacao");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("titulo");

                    b.HasKey("Id")
                        .HasName("pk_imoveis");

                    b.HasIndex("OrganizacaoId")
                        .HasDatabaseName("ix_imoveis_organizacao_id");

                    b.HasIndex("OrganizacaoId", "CodigoDeReferencia")
                        .IsUnique()
                        .HasDatabaseName("ix_imoveis_organizacao_id_codigo_de_referencia");

                    b.ToTable("imoveis", (string)null);
                });

            modelBuilder.Entity("Morpheus.Dominio.Organizacoes.Organizacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.HasKey("Id")
                        .HasName("pk_organizacoes");

                    b.ToTable("organizacoes", (string)null);
                });

            modelBuilder.Entity("Morpheus.Infraestrutura.Identidade.UsuarioDaOrganizacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("access_failed_count");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("email_confirmed");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("lockout_enabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end");

                    b.Property<string>("NomeCompleto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome_completo");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_user_name");

                    b.Property<Guid>("OrganizacaoId")
                        .HasColumnType("uuid")
                        .HasColumnName("organizacao_id");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("phone_number_confirmed");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text")
                        .HasColumnName("security_stamp");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("two_factor_enabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_usuarios");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.HasIndex("OrganizacaoId")
                        .HasDatabaseName("ix_usuarios_organizacao_id");

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("Morpheus.Infraestrutura.Persistencia.Outbox.MensagemDeOutbox", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Conteudo")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("conteudo");

                    b.Property<DateTimeOffset>("OcorridoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ocorrido_em");

                    b.Property<Guid>("OrganizacaoId")
                        .HasColumnType("uuid")
                        .HasColumnName("organizacao_id");

                    b.Property<DateTimeOffset?>("ProcessadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processado_em");

                    b.Property<string>("TipoDoEvento")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("tipo_do_evento");

                    b.HasKey("Id")
                        .HasName("pk_mensagens_outbox");

                    b.HasIndex("OrganizacaoId")
                        .HasDatabaseName("ix_mensagens_outbox_organizacao_id");

                    b.HasIndex("ProcessadoEm", "OcorridoEm")
                        .HasDatabaseName("ix_mensagens_outbox_processado_em_ocorrido_em");

                    b.ToTable("mensagens_outbox", (string)null);
                });

            modelBuilder.Entity("Morpheus.Infraestrutura.Sessoes.SessaoDoPainelArmazenada", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<byte[]>("Conteudo")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("conteudo");

                    b.Property<DateTimeOffset>("CriadaEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criada_em");

                    b.Property<DateTimeOffset>("ExpiraEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expira_em");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("pk_sessoes");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("ix_sessoes_usuario_id");

                    b.ToTable("sessoes", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_claims_roles_role_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Morpheus.Infraestrutura.Identidade.UsuarioDaOrganizacao", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_claims_usuarios_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Morpheus.Infraestrutura.Identidade.UsuarioDaOrganizacao", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_logins_usuarios_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_roles_role_id");

                    b.HasOne("Morpheus.Infraestrutura.Identidade.UsuarioDaOrganizacao", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_usuarios_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Morpheus.Infraestrutura.Identidade.UsuarioDaOrganizacao", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_tokens_usuarios_user_id");
                });

            modelBuilder.Entity("Morpheus.Dominio.Imoveis.Imovel", b =>
                {
                    b.HasOne("Morpheus.Dominio.Organizacoes.Organizacao", null)
                        .WithMany()
                        .HasForeignKey("OrganizacaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_imoveis_organizacoes_organizacao_id");

                    b.OwnsOne("Morpheus.Dominio.Comum.DadosDeAuditoria", "Auditoria", b1 =>
                        {
                            b1.Property<Guid>("ImovelId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<DateTimeOffset>("AtualizadoEm")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("atualizado_em");

                            b1.Property<DateTimeOffset>("CriadoEm")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("criado_em");

                            b1.HasKey("ImovelId");

                            b1.ToTable("imoveis");

                            b1.WithOwner()
                                .HasForeignKey("ImovelId")
                                .HasConstraintName("fk_imoveis_imoveis_id");
                        });

                    b.Navigation("Auditoria")
                        .IsRequired();
                });

            modelBuilder.Entity("Morpheus.Dominio.Organizacoes.Organizacao", b =>
                {
                    b.OwnsOne("Morpheus.Dominio.Organizacoes.ConfiguracaoDaOrganizacao", "Configuracao", b1 =>
                        {
                            b1.Property<Guid>("OrganizacaoId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("FusoHorario")
                                .IsRequired()
                                .HasMaxLength(60)
                                .HasColumnType("character varying(60)")
                                .HasColumnName("fuso_horario");

                            b1.HasKey("OrganizacaoId");

                            b1.ToTable("organizacoes");

                            b1.WithOwner()
                                .HasForeignKey("OrganizacaoId")
                                .HasConstraintName("fk_organizacoes_organizacoes_id");

                            b1.OwnsOne("Morpheus.Dominio.Organizacoes.JanelaDeAtendimento", "JanelaDeAtendimento", b2 =>
                                {
                                    b2.Property<Guid>("ConfiguracaoDaOrganizacaoOrganizacaoId")
                                        .HasColumnType("uuid")
                                        .HasColumnName("id");

                                    b2.Property<TimeOnly>("Fim")
                                        .HasColumnType("time without time zone")
                                        .HasColumnName("atendimento_fim");

                                    b2.Property<TimeOnly>("Inicio")
                                        .HasColumnType("time without time zone")
                                        .HasColumnName("atendimento_inicio");

                                    b2.HasKey("ConfiguracaoDaOrganizacaoOrganizacaoId");

                                    b2.ToTable("organizacoes");

                                    b2.WithOwner()
                                        .HasForeignKey("ConfiguracaoDaOrganizacaoOrganizacaoId")
                                        .HasConstraintName("fk_organizacoes_organizacoes_id");
                                });

                            b1.Navigation("JanelaDeAtendimento")
                                .IsRequired();
                        });

                    b.OwnsOne("Morpheus.Dominio.Comum.DadosDeAuditoria", "Auditoria", b1 =>
                        {
                            b1.Property<Guid>("OrganizacaoId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<DateTimeOffset>("AtualizadoEm")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("atualizado_em");

                            b1.Property<DateTimeOffset>("CriadoEm")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("criado_em");

                            b1.HasKey("OrganizacaoId");

                            b1.ToTable("organizacoes");

                            b1.WithOwner()
                                .HasForeignKey("OrganizacaoId")
                                .HasConstraintName("fk_organizacoes_organizacoes_id");
                        });

                    b.Navigation("Auditoria")
                        .IsRequired();

                    b.Navigation("Configuracao")
                        .IsRequired();
                });

            modelBuilder.Entity("Morpheus.Infraestrutura.Identidade.UsuarioDaOrganizacao", b =>
                {
                    b.HasOne("Morpheus.Dominio.Organizacoes.Organizacao", null)
                        .WithMany()
                        .HasForeignKey("OrganizacaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_usuarios_organizacoes_organizacao_id");
                });

            modelBuilder.Entity("Morpheus.Infraestrutura.Sessoes.SessaoDoPainelArmazenada", b =>
                {
                    b.HasOne("Morpheus.Infraestrutura.Identidade.UsuarioDaOrganizacao", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sessoes_usuarios_usuario_id");
                });
#pragma warning restore 612, 618
        }
    }
}
